### ISSUE TITLE
Support mongo repositories aggregation

### ISSUE THREAD

**Issue by chlegou** [turkraft/springfilter#130]
ENHANCEMENT:

> [Spring boot mongo repositories aggregation](https://github.com/spring-projects/spring-data-mongodb/blob/main/src/main/asciidoc/reference/mongo-repositories-aggregation.adoc) offer means to interact with the aggregation framework via annotated repository query methods. Similar to the JSON based queries, you can define a pipeline using the org.springframework.data.mongodb.repository.Aggregation annotation. 

I'm suggesting that you should enhance your library to support aggregation pipeline:  

now your library could be used like this: **(working example)**

    // controller
    @GetMapping("")
    public Page<Entity> filter(@Filter(entityClass = Entity.class) Document document, Pageable pageable) {
        return repository.filter(document, pageable);
    }
    // repository
    @Query("?0")
    Page<Entity> filter(Document document, Pageable pageable);

mongo repositories aggregation annotation `@Aggregation` accepts 2 types of arguments:  
- String: simple aggregation query.  (manu examples are available in official doc, the link above).
- String[]: aggregation queries pipeline.  

example format of aggregation queries pipeline

    // it returns list, can't return page. limitation by official library
    @Aggregation({
      "{ $match : {.......},",
      "{$addFields:{.......}",
      "{'$unwind':'$field'}",
      "{$group:{.......}",
      "{'$sort':{'_id':-1}}",
      "{$project:{......}",
    })
    List<dataDTO> exampleOfAggregationPipeline(ParamTypeObject params... , Pageable pageable);

#### current usage of your library with Aggregation:

your library could be used currently with aggregation to the `$match` only.

    @Aggregation({
      "{ $match : ?0 ,",
      "{$addFields:{.......}",
      "{'$unwind':'$field'}",
      "{$group:{.......}",
      "{'$sort':{'_id':-1}}",
      "{$project:{......}",
    })
    List<dataDTO> exampleOfAggregationPipeline(Document document, ParamTypeObject params... , Pageable pageable);

#### enhancement of your library with Aggregation: (suggestions)

**IMPORTANT:  be aware that `@Aggregation("?0")` is referring to `simple aggregation query` which accepts String type and not activating aggregation  pipelines.**
    
    @Aggregation() or @Aggregation("[0]") or @Aggregation("#0") or @Aggregation("#0")
    List<dataDTO> exampleOfAggregationPipeline(List<Document> document, ParamTypeObject params... , Pageable pageable);
    // or to simplify it, params could be added from the query builder.
    List<dataDTO> exampleOfAggregationPipeline(List<Document> document , Pageable pageable);

This should be outstanding, and more flexible solution.

Hope you like it, and work on it :)

**Comment by chlegou** [comment]
https://github.com/spring-projects/spring-data-mongodb/issues/3857

**Comment by torshid** [comment]
Hi @chlegou 

The new version supports Mongo aggregations. You can implement your custom operator/function if needed:

```java
@Component
public class CustomFunction extends FilterFunction {

  protected CustomFunction() {
    super("customFunction");
  }

}
```

```java
@Component
class CustomFunctionJsonNodeProcessor implements
    FilterFunctionProcessor<FilterJsonNodeTransformer, JsonNode> {

  @Override
  public Class<FilterJsonNodeTransformer> getTransformerType() {
    return FilterJsonNodeTransformer.class;
  }

  @Override
  public Class<CustomFunction> getDefinitionType() {
    return CustomFunction.class;
  }

  @Override
  public JsonNode process(FilterJsonNodeTransformer transformer, FunctionNode source) {
    // https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/
    // return transformer.getObjectMapper().createObjectNode() ...
  }

}
```

Support for the `@Aggregation` annotation is out of scope for now though.
