### ISSUE TITLE
👍 Filtering nested collections; agregation/window functions; request examples 👍

### ISSUE THREAD

**Issue by alex1v1adamov** [turkraft/springfilter#219]
First of all, I want to thank you for such a great tool! It is not clear to me why in such a developed Spring ecosystem there is no tool that provides REST query lanquage out-of-the-box. I have tried RSQL with extentions, QueryDSL with value oparators and now see that this tool has great potential to be the first choice.

Secondly, I want to ask you to add more examples of the use-cases various elements and their interaction to the swagger

I can't use spring-filter now because it lacks a critical functionality for filtering by nested collections. I try to explain ruge by examples, from more critical to less (by swagger):

1) /employee?filter=stuff.firstName:Maurine - return that employees who get in stuff person with firstName "Maurine"
1.1) /employee?filter=stuff.salary > 10000 - return that employees who got any stuff with salary more then 10000
1.2) /employee?filter=all(stuff.salary) > 10000 - return that employees who got all stuff with salary more then 10000

2) /employee?filter=sum(salary) < 20000  - return employees globally limited by sum of their salary by 20000  

like in postgres:

SELECT *
FROM
  (SELECT *, sum(salary) OVER (ORDER BY salary) AS sumSalary FROM employee) AS emp
WHERE sumSalary < 20000 ;

2.1) /employee?filter=staff.sum(salary) < 15000  - return that employees whos all staff sum sallary less 15000
2.2) /employee?filter=sum(staff.salary) < 15000  - return employees globally limited by sum of their staff salary by 20000

**Comment by torshid** [comment]
Hi @alex1v1adamov 

These queries should work as expected in the latest versions of the library:

```
/employee?filter=stuff.firstName:'Maurine'
/employee?filter=stuff.salary > 10000
/employee?filter=sum(salary) < 20000
/employee?filter=sum(staff.salary) < 15000
```

But the SQL query you provided is too complicated, not sure how the filter query should look like here... you can always create your own filter functions, it would look nicer than SQL anyways.

Closing this for now, feel free to open other issues.
