### ISSUE TITLE
exclude the filters on unavailable fields (like the fields with @Transient)

### ISSUE THREAD

**Issue by 8fatemeT8** [turkraft/springfilter#248]
hello 

In the first thanks a lot for your amazing library 😄 

My issue is about filtering transient fields and obviously these fields are not present in my table
so the jpa repository throw exception when I send specification in findAll method

**Comment by torshid** [comment]
Hi @8fatemeT8 

What would you want the library to do instead of throwing an exception? This behavior seems right to me.

**Comment by 8fatemeT8** [comment]
I think it's better to ignore it instead of throw an exception.
and the programmer must handle the specification of the transient field.
