### ISSUE TITLE
Add support for @Embedded / @Embeddable objects as nested fields

### ISSUE THREAD

**Issue by ddewaele** [turkraft/springfilter#271]
I noticed that the library is unable to filter on `@Embedded` objects

The following code in `ExpressionHelperImpl` only allows nested properties that are part of the entity manager (standard JPA collections with Entities :
```
  private boolean shouldJoin(Path<?> path) {
    return path.getModel().getBindableType() == BindableType.PLURAL_ATTRIBUTE
        || (path.getModel().getBindableType() == BindableType.SINGULAR_ATTRIBUTE
        && isEntityType(path.getModel().getBindableJavaType()));
  }
```

As `Embeddable` are not `Entity` types, they are unable to be joined / queried.

We have objects with `Embedded` objects like this : 

```
    @NotNull
    @Embedded
    @Valid
    private Address address;
```

with an `Embeddable`
```
@Embeddable
@Data
public class Address {

    private String streetAndNumber;
    private String postalCode;
    private String city;
    private String country;

}
```

That we are unable to query via `address.country` for example.

**Comment by torshid** [comment]
Done in https://github.com/turkraft/springfilter/releases/tag/3.0.5.

**Comment by ddewaele** [comment]
Thx a lot ! Works fine.
