### ISSUE TITLE
Allow customization of argument resolvers

### ISSUE THREAD

**Issue by steinmaerivoet** [turkraft/springfilter#274]
We want to customize the argument resolvers so we can use our own annotation in the controller methods, and wrap some extra domain specific logic.

Is it possible to make the argument resolver classes (FilterNodeArgumentResolver, FilterSpecificationArgumentResolver) and constructors public. And also make the private fields protected?

Thanks in advance!
Stein, developer@Ixor

**Comment by torshid** [comment]
Hi @steinmaerivoet 

Available in https://github.com/turkraft/springfilter/releases/tag/3.0.6.

**Comment by steinmaerivoet** [comment]
@torshid Thank you for the fast support!

**Comment by steinmaerivoet** [comment]
The constructors are still package private, so extending is still not possible

**Comment by torshid** [comment]
You are right, not sure why these constructors were private in the first place...

Fixed in https://github.com/turkraft/springfilter/releases/tag/3.0.7.
