### ISSUE TITLE
Error Filter

### ISSUE THREAD

**Issue by akbartrinanda** [turkraft/springfilter#278]
i got this error

> java: cannot access com.turkraft.springfilter.boot.Filter
  bad class file: /C:/Users/Artand/.m2/repository/com/turkraft/springfilter/core/3.0.7/core-3.0.7.jar!/com/turkraft/springfilter/boot/Filter.class
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by torshid** [comment]
Hi,

It is because your project is not configured to support Java 17.
