### ISSUE TITLE
Mismatched input `,` with the IN operator

### ISSUE THREAD

**Issue by barthofu** [turkraft/springfilter#281]
I use this library with JPA, and when i try a request like the following:
```
/reporting/search/evenement?filter=type.libelle in ('Danger', 'Autre')
```
It fails with this error:
```json
{
    "timestamp": "2023-04-18T09:47:00.418+00:00",
    "message": "mismatched input ',' expecting {INFIX_OPERATOR, POSTFIX_OPERATOR, ')'}",
    "code": "500 INTERNAL_SERVER_ERROR",
    "details": "uri=/api/reporting/search/evenement",
    "user": null
}
```

But it succeeds when i put only one element in the `()` array like the following:
```
/reporting/search/evenement?filter=type.libelle in ('Danger')
```

Finaly, when i try with braces instead of parenthesis like this:
```
/reporting/search/evenement?filter=type.libelle in ['Danger' , 'Autre']
```
I get a Spring 400 Bad Request error page (the reponse is purely HTML)

---

_Versions:_

springfilter: `3.0.7`
spring boot: `latest`
java: `18`

**Comment by torshid** [comment]
The correct syntax is `type.libelle in ['Danger' , 'Autre']` but you may need to encode the brackets: `type.libelle in %5B'Danger' , 'Autre'%5D`.

**Comment by barthofu** [comment]
Thanks it works!
