### ISSUE TITLE
`*` in `like` operator (`~`) doesn't act as an all-matching pattern

### ISSUE THREAD

**Issue by barthofu** [turkraft/springfilter#283]
When I make a request with, for example, this filter:
```
?filter=type.libelle ~ 'Dang*'
```
with effective rows in my database that match the pattern, it doesn't return anything.

### Things I noticed

- There is the same problem with the `~~` operator
- A request with `type.libelle ~ '*Danger*'` won't work while one with `type.libelle ~ 'Danger'` works as expected
- After checking my Spring's logs, i noticed that it sent as it is in the SQL query, shouldn't the `*` be replaced with `%` at this moment as it seems to use the SQL `LIKE` operator?
- I tried by putting `%` instead of `*` in my request, didn't work (the `LIKE` operator of the SQL query wasn't here at all)
- I tried by encoding the `*` using `%2A`, same problem (it is well parsed tho, the `*` reappears in the SQL query at the end)
- Sample of the SQL query log: `where t1_0.libelle like 'Dang*' escape ''`

---

_Versions:_

springfilter: `3.0.7`
spring boot: `latest`
java: `18`

**Comment by torshid** [comment]
Hi @barthofu,

Thanks for notifying about this. You should be able to use your initial filter `?filter=type.libelle ~ 'Dang*'` in the latest version https://github.com/turkraft/springfilter/releases/tag/3.0.8.
