### ISSUE TITLE
Possible multithreading issue with converting dates

### ISSUE THREAD

**Issue by nazar-phokus** [turkraft/springfilter#286]
Hi, 

I think there is a possible multithreading issue with converting dates.

FilterParameters defines a static SimpleDateFormat instance that is accessible from StringConverter.
```
public class FilterParameters {

public static SimpleDateFormat DATE_FORMATTER;
static {

    DATE_FORMATTER = new SimpleDateFormat("dd-MM-yyyy");
...
}
...
}
```

SimpleDateFormat is not thread-safe, according to the Java Doc

```
Synchronization
Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.
API Note:
Consider using java.time.format.DateTimeFormatter as an immutable and thread-safe alternative.
```

There was similar issue before for NumberFormat NUMBER_FORMAT, but was fixed in version **2.1.2** (https://github.com/turkraft/springfilter/releases/tag/2.1.2)

Thanks,
Nazariy

**Comment by torshid** [comment]
Hi @nazar-phokus,

Which version are you using? The library does handle conversions anymore and instead relies on Spring's ConversionService, the FilterParameters class does not exist in the latest versions.

**Comment by nazar-phokus** [comment]
Hello @torshid, we are using 2.1.4.

**Comment by torshid** [comment]
Should be fixed in https://github.com/turkraft/springfilter/releases/tag/2.1.6.

**Comment by nazar-phokus** [comment]
Thanks @torshid !
