### ISSUE TITLE
Update Javascript Query Builder example

### ISSUE THREAD

**Issue by sisimomo** [turkraft/springfilter#289]
Hi,

I recently updated the JavaScript/TypeScript Query Builder to its [first stable version](https://github.com/sisimomo/Spring-Filter-Query-Builder/releases/tag/v1.0.0). Some things have changed. Here is an updated version of a snippet for your documentation:
```js
import { sfAnd, sfEqual, sfGt, sfIsNull, sfLike, sfNot, sfOr } from 'spring-filter-query-builder';

const filter = sfAnd([
  sfAnd([sfEqual('status', 'active'), sfGt('createdAt', '1-1-2000')]),
  sfOr([sfLike('value', '*hello*'), sfLike('name', '*world*')]),
  sfNot(sfOr([sfGt('id', 100), sfIsNull('category.order')])),
]);

const req = await fetch('http://api/person?filter=' + filter.toString());
```

Have a great day!

**Comment by torshid** [comment]
Hello @sisimomo, looks great! Thanks.
