### ISSUE TITLE
Opportunity to use functions on the right side of the comparators

### ISSUE THREAD

**Issue by zhenyabodukhin** [turkraft/springfilter#316]
Is it possible to use functions on the right side of the comparators? For example accidentsNumberRequired:size(accidents)

**Comment by torshid** [comment]
Hi @zhenyabodukhin,

Sorry for the delay. This should already work with Spring Filter 3.x.x.

`accidentsNumberRequired : size(accidents)` is equivalent to `size(accidents) : accidentsNumberRequired`.

Feel free to reopen if you see something wrong.
