### ISSUE TITLE
Add new module for deserialization in the @Filter annotation

### ISSUE THREAD

**Issue by sondavide** [turkraft/springfilter#327]
Hi, I'm using the last release  3.1.5:

<dependency>
	<groupId>com.turkraft.springfilter</groupId>
	<artifactId>mongo</artifactId>
	<version>3.1.5</version>
</dependency>

There is a way to register a new or custom module in the ObjectMapper deserializers?

If I have a class with a field of type Instant, this error comes out:

"Query: { "$expr" : { "$gte" : ["$instant", "[ERROR: (com.fasterxml.jackson.databind.exc.InvalidDefinitionException) Java 8 date/time type `java.time.Instant` not supported by default: add Module \"com.fasterxml.jackson.datatype:jackson-datatype-jsr310\" to enable handling]"]}}, Fields: {}, Sort: {}"

There's a way to add jackson-datatypee-jsr310?

**Comment by torshid** [comment]
Hi @sondavide,

Spring Filter simply autowires the present ObjectMapper bean, without making any configuration to it. You may customize that behavior as it may be done in any Spring project, [see this for example](https://www.baeldung.com/spring-boot-customize-jackson-objectmapper).

**Comment by sondavide** [comment]
Hi @torshid , thanks for the help. 
I'm trying to understand the problem, it's not a deserialization problem, because in the JsonNodeHelperImpl has the correct ObjectMapper and the rightResult in the transform function is of type Instant.
If I use the classic mongo repository query:
```
    @Query("{$expr: {$eq: ['$DATA_INSTALLAZIONE', ?0 ]}}")
    List<Civic> getByDate(Instant data);
```
    
it works and finds the correct datas, if  I use the @Filter annotation, something does not work

**Comment by sondavide** [comment]
finally I used a custom converter:

```

@Service
public class CustomInstantConverter implements Converter<String, CustomInstant> {

  @Override
  public CustomInstant convert(String source) {
    return new CustomInstant(source);
  }

  @Data
  @NoArgsConstructor
  public static class CustomInstant implements Serializable {

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DateFromString implements Serializable{
        public String dateString;
    }


    @JsonProperty("$dateFromString")
    public DateFromString dateFromString;

    public CustomInstant(String source) {
        this.dateFromString= new DateFromString(source);
    }


  }


}
```

$dateFromString saved me

**Comment by torshid** [comment]
Thanks for sharing the solution!
