### ISSUE TITLE
Query in relations

### ISSUE THREAD

**Issue by pedrammehrdad** [turkraft/springfilter#375]
I want to list companies that give all employees a salary of more than 3000.
The first thing that comes to mind is to write a filter like the following:
`employees.salary >3000 `
but this will list companies that have a salary of more than 3000. so I changed the query to the following:
`employees.salary >3000 and not(employees.salary < 3000)`
This is also not working as expected.
Is there a way to achieve this?

**Comment by torshid** [comment]
This should do the job: `not exists(employees.salary < 3000)`
