### ISSUE TITLE
How to set require false in swagger?

### ISSUE THREAD

**Issue by abccbaandy** [turkraft/springfilter#381]
In this issue
https://github.com/turkraft/springfilter/issues/177

````java
List<Entity> listEntities(@Parameter(in = ParameterIn.QUERY, name = "filter", description = "Filter query", schema = @Schema(type = "string")) @Filter Specification<Entity> spec) {
 // ...
}
````
We can use `@Parameter` to show correct format in swagger, but even with `require = false`, it still be required in swagger.

I try with `@RequestParam` with require false, but it will make the whole filter not work(the filter will be always null).

**Comment by torshid** [comment]
Are you using version 3.x?

**Comment by torshid** [comment]
There should be similar classes to achieve the same goal in 2.x. It's a workaround yes but I don't see any other way to do it currently since it's a problem with springdoc, using String gives you more flexibility. You can also write your own interceptors.
