### ISSUE TITLE
Backslash Query Issue

### ISSUE THREAD

**Issue by 4ntP3d** [turkraft/springfilter#382]
Hi, 
I'm currently using version 2.x.x of the software. 
I've encountered an issue where it seems impossible to pass the backslash "\" character as a value in a query. To elaborate, when I attempt to send the query "description~'*\\*'", I receive an error during the filter conversion process. The error message reads: "token recognition error at: ''*\\*'". However, when I query "description~'*\\\\*'", everything works perfectly. This leads me to question how I should proceed if I need to search for a record that contains a single backslash within one of its properties. Any guidance would be greatly appreciated. Thank you.

**Comment by torshid** [comment]
When you query `description~'\\'`, is it sending two backslashes to the database? I think it should send only one.

2.x is not supported anymore by the way, I recommend you upgrade to 3.x which is much more flexible.
