### ISSUE TITLE
How to re-format datetime when searching?

### ISSUE THREAD

**Issue by MixueCN** [turkraft/springfilter#396]
The field **createdDate** is of timestamp type. When I pass the filter parameter as createdDate > '17-07-2024', I receive an SQL Error "date/time field value out of range: '17-07-2024'". I can make adjustments in version 2.1.5, but I'm unsure where to make changes for version 3. Thank you.

**Comment by torshid** [comment]
Conversions are handled by Spring's ConversionService in version 3.
