### ISSUE TITLE
I can't query when the enum saved in the db is a string 

### ISSUE THREAD

**Issue by DuncanNguyez** [turkraft/springfilter#417]
Hi,
I can't query when the enum saved in the db is a string
Currently it always converts to an ordinal number. Is there a way to adjust query behavior accordingly?

**Comment by bboulahdid** [comment]
I have a similar issue. In my entity class, I have an enum field annotated with `@Enumerated(EnumType.STRING)` but when I filter on this field I get this error: `ORA-01722: invalid number`.

And when I check the the generated query I see that the field is treated as a number: `... where x=10` (10 is the ordinal value of the enum value).
